- url: /
  controller: TestProject\Controller\LandingPage\RandomIntro
- url: /testing
  controller: TestProject\Controller\Test\Testing
- url: /sqlConnect
  controller: TestProject\Controller\mySQLConnect\Connect
- url: /addCounties 
  controller: TestProject\Controller\Import\Location
- url: /countyCityImport
  controller: TestProject\Controller\Import\CountyAndCityImport
- url: /wikiImport  
  controller: TestProject\Controller\Import\WikiImport
- url: /mostPopular
  controller: TestProject\Controller\Statistics\MostPopularPage
- url: /highestBandwithUsage
  controller: TestProject\Controller\Statistics\HighestBWUsage
- url: /temperature
  controller: TestProject\Controller\Statistics\MaxTemperature
- url: /counties-and-cities
  controller: TestProject\Controller\Statistics\County_City_Stats