- url: /
  controller: LandingPage\RandomIntro
  
- url: /testing
  controller: Test\Testing
  
- url: /sqlConnect
  controller: mySQLConnect\Connect
  
- url: /addCounties 
  controller: Import\Location
  
- url: /countyCityImport
  controller: Import\CountyAndCityImport
  
- url: /wikiImport  
  controller: Import\WikiImport
  
- url: /mostPopular
  controller: Statistics\MostPopularPage
  
- url: /highestBandwithUsage
  controller: Statistics\HighestBWUsage
  
- url: /temperature
  controller: Statistics\MaxTemperature
  
- url: /counties-and-cities
  controller: Statistics\County_City_Stats

- url: /counties/add
  controller: Counties\Add
  
- url: /counties/action_page
  controller: Counties\action_page.php

- url: /counties/delete
  controller: Counties\Delete