- url: /home2
  method: get
  controller: Location\County
  function: home

- url: /counties/AddCounty
  method: get
  controller: Location\County
  function: addCounty
  
- url: /counties/AddCounty
  method: post
  controller: Location\County
  function: addCounty

- url: /counties/edit/{id}
  method: get
  controller: Location\County
  function: editCounty
  
- url: /counties/edit/{id}
  method: post
  controller: Location\County
  function: editCounty  
  
- url: counties/delete/{id}
  method: get
  controller: Location\County
  function: deleteCounty
  
- url: cities/map
  method: get
  controller: Location\City
  function: mapCity
  
- url: cities/map
  method: post
  controller: Location\City
  function: mapCity
  
- url: cities/map/search
  method: get
  controller: Location\City
  function: searchCity

- url: cities/map/search
  method: post
  controller: Location\City
  function: searchCity

- url: cities/map/search2
  method: get
  controller: Location\City
  function: searchCity2

- url: cities/map/search2
  method: post
  controller: Location\City
  function: searchCity2
  
- url: /cities/map/search2?{id}
  method: get
  controller: Location\City
  function: searchCity2
  
- url: /cities/map/search2?{id}
  method: post
  controller: Location\City
  function: searchCity2
  
- url: /cities/map/success
  method: get
  controller: Location\City
  function: mapNewCity
  
- url: cities/{id}   
  method: get
  controller: Location\City
  function: cityList
  
- url: /cities/{id}/AddCity
  method: post
  controller: Location\City
  function: addCity
  
- url: /cities/{id}/AddCity
  method: get
  controller: Location\City
  function: addCity
    
- url: /cities/delete/{id}    
  method: get
  controller: Location\City
  function: deleteCity
  
    
    
    
- url: /randomNr
  method: get
  controller: LandingPage\RandomIntro
  
- url: /testing
  method: get
  controller: Test\Testing
  
- url: /sqlConnect
  method: get
  controller: mySQLConnect\Connect
  
- url: /addCounties
  method: get
  controller: Import\Location
  
- url: /countyCityImport
  method: get
  controller: Import\CountyAndCityImport
  
- url: /wikiImport
  method: get
  controller: Import\WikiImport
  
- url: /mostPopular
  method: get
  controller: Statistics\MostPopularPage
  
- url: /highestBandwithUsage
  method: get
  controller: Statistics\HighestBWUsage
  
- url: /temperature
  method: get
  controller: Statistics\MaxTemperature
  
- url: /counties-and-cities
  method: get
  controller: Statistics\County_City_Stats



  
  